# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x07weather\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"7\n\x17TokenValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\\\n\x0b\x41uthService\x12M\n\x12isAccessTokenValid\x12\x15.weather.TokenRequest\x1a .weather.TokenValidationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOKENREQUEST']._serialized_start=26
  _globals['_TOKENREQUEST']._serialized_end=55
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_start=57
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_end=112
  _globals['_AUTHSERVICE']._serialized_start=114
  _globals['_AUTHSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
